### ISSUE TITLE
Create card get TypeError: (0 , navigation.useParams) is not a function

### ISSUE THREAD

**Issue by sxadxsx** [fuma-nama/next-docs#166]
I add a card to my content/docs/index.mdx and I get <html>
```
TypeError: (0 , navigation.useParams) is not a function
--
22:25:52.314 | at SafeLink (/vercel/path0/.next/server/chunks/9983.js:30641:42)
22:25:52.315 | at Be (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:106:273)
22:25:52.315 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:112:91)
22:25:52.315 | at Be (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:107:9)
22:25:52.315 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:112:91)
22:25:52.315 | at Ce (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:114:98)
22:25:52.315 | at Ee (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:113:424)
22:25:52.315 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:112:222)
22:25:52.315 | at Ce (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:114:98)
22:25:52.315 | at Be (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:107:215)
```

how to fix it

**Comment by fuma-nama** [comment]
How do you add the card? Please provide sufficient information to reproduce your project.

**Comment by peteryang1756** [comment]
this is my code: https://github.com/ssangyongsportsorg/Ssport-website/blob/main/content/docs/index.mdx

**Comment by sxadxsx** [comment]
this is my code: https://github.com/ssangyongsportsorg/Ssport-website/blob/main/content/docs/index.mdx

**Comment by fuma-nama** [comment]
I noticed that you're using a deprecated version of Next Docs, the `SafeLink` API has been removed since 4.0.0, can you upgrade and try again?

**Comment by fuma-nama** [comment]
Also, the App Router feature in Next.js 13.2.4 is not stable yet, please update to Next.js 13.4+
